### ISSUE TITLE
Not strictly an issue, but having problems running.. help please

### ISSUE THREAD

**Issue by CatspersCoffee** [evdubs/nasdaq-symbols#2]
Hi evdubs,
Im having an issue running transform-load.rkt, im trying to use it with QuestDB and have changed the relevant database credentials. extract.rkt works correctly and i have nasdaqtraded.2020-07-03.txt in /var/tmp/nasdaq, however when i run transform-load.rkt i get:

``` $ racket transform-load.rkt
parse-command-line: expected argument of type <table as a list of flag-list/procedure pairs (no pre-defined flags: "-h")>; given: '((once-each (("-d" "--file-date") #<procedure:...cket/cmdline.rkt:141:76> (("Nasdaq file date. Defaults to today") "date-str")) (("-n" "--db-name") #<procedure:...cket/cmdline.rkt:141:76> (("Database name. Defaults to 'qdb'") "name")) (("-p" "--db-pass...
  context...:
   /usr/share/racket/collects/racket/cmdline.rkt:266:10: for-loop
   /usr/share/racket/collects/racket/cmdline.rkt:257:4: for-loop
   /usr/share/racket/collects/racket/cmdline.rkt:251:2: for-loop
   /usr/share/racket/collects/racket/cmdline.rkt:229:0: parse-command-line10
   /home/user/options_data/nasdaq-symbols/transform-load.rkt: [running body]
```

have also tried to run the .sh script.. but get the same result.

any help would be appreciated. thankyou

**Comment by CatspersCoffee** [comment]
Ok so after testing this on a standard Postgres database (not QuestDB), i can run a test program to connect.. which suggests that there is an issue with the Postgres wire protocol in Quest. However. running transform-load.rkt i now get an error:


**query-exec: schema "nasdaq" does not exist**

```
./extract-transform-load.sh
rename-file-or-directory: cannot rename file or directory;
 the destination path already exists
  source path: /var/tmp/nasdaq/nasdaqtraded.txt
  dest path: /var/tmp/nasdaq/nasdaqtraded.2020-07-03.txt
  context...:
   "/home/user/options/extract.rkt": [running body]
   temp37_0
   for-loop
   run-module-instance!125
   perform-require!78
query-exec: schema "nasdaq" does not exist
  SQLSTATE: 3F000
  context...:
   /usr/share/racket/collects/db/private/generic/interfaces.rkt:170:0: raise-sql-error
   .../more-scheme.rkt:261:28
   /usr/share/racket/collects/db/private/generic/common.rkt:277:13
   /usr/share/racket/collects/db/private/generic/../../../racket/private/more-scheme.rkt:261:28
   /usr/share/racket/collects/db/private/generic/functions.rkt:90:0: compose-statement
   /usr/share/racket/collects/db/private/generic/functions.rkt:148:0: query-exec
   /home/user/options/transform-load2.rkt:68:11
   /usr/share/racket/collects/racket/private/sequence.rkt:33:2: for-loop
   /usr/share/racket/collects/racket/private/sequence.rkt:30:0: sequence-for-each
   "/home/user/options/transform-load2.rkt": [running body]
   temp37_0
   for-loop
   run-module-instance!125
   perform-require!78
./extract-transform-load.sh: line 10: 7zr: command not found
```

**Comment by evdubs** [comment]
You'll need to create the nasdaq schema:

```sql
create schema nasdaq;
```

Then, you'll need to add the types and tables for the nasdaq schema. This is done by executing all of the code in `schema.sql`.

**Comment by CatspersCoffee** [comment]
Awesome thanks for that, now i get:
```Inserted or updated 8921 rows```

Have you had any luck with QuestDB or any other Time Series DBMS ?

**Comment by evdubs** [comment]
> Have you had any luck with QuestDB or any other Time Series DBMS ?

I took a brief look at TimescaleDB a while ago, but things seemed to work well enough without needing a different storage engine. Maybe the most significant analysis I do with this data is backtesting. Trying to implement a backtester in `plpgsql` seemed clunky, but I can certainly see that there could be performance improvements trying to do more computation on the database side, especially with a more clever storage engine.

**Comment by CatspersCoffee** [comment]
fair enough.
forgive me but im having trouble with the other two programs. spdr-etf and invesco, do i need to:

```create schema spdr;```

and

```create schema invesco ;```

then load the ```schema.sql``` for each respectively?

thanks for your help, i appreciate it

**Comment by CatspersCoffee** [comment]
unfortunately when running spdr extraction .sh seem to be getting the error:

```~/spdr_options/spdr-etf-holdings$ ./extract-transform-load.sh
standard-module-name-resolver: collection not found
  for module path: tasks
  collection: "tasks"
  in collection directories:
   /home/user/.racket/7.2/collects
   /usr/share/racket/collects
   ... [174 additional linked and package directories]
  context...:
   show-collection-err
   standard-module-name-resolver
   perform-require!78
   for-loop
   finish
   [repeats 6 more times]
   pass-1-and-2-loop
   module-begin-k
   expand-module16
   expand-capturing-lifts
   temp118_0
   temp91_0
   compile15
   temp85_0
   standard-module-name-resolver
   module-path-index-resolve
   ...
directory-list: could not open directory
  path: /var/tmp/spdr/etf-holdings/2020-07-03/
  system error: No such file or directory; errno=2
  context...:
   /usr/share/racket/collects/racket/private/for.rkt:2229:7
   /usr/share/racket/collects/racket/private/for.rkt:530:2: make-sequence
   /usr/share/racket/collects/racket/private/for.rkt:1400:2: sequence-generate*
   /usr/share/racket/collects/racket/sequence.rkt:140:7
   /usr/share/racket/collects/racket/private/for.rkt:530:2: make-sequence
   "/home/user/spdr_options/spdr-etf-holdings/transform-load-csv.rkt": [running body]
   temp37_0
   for-loop
   run-module-instance!125
   perform-require!78
./extract-transform-load.sh: line 13: 7zr: command not found
```

**Comment by evdubs** [comment]
You'll need to `create schema` for each of the different projects. I should probably add that to each of the schema.sql files.

With respect to "collection not found ... tasks", each project has in the Readme a section like:

> Dependencies
> It is recommended that you start with the standard Racket distribution. With that, you will need to install the following packages:
> `$ raco pkg install --skip-installed gregor tasks threading`

Please make sure to run that to get the appropriate dependencies.

**Comment by CatspersCoffee** [comment]
oh right, i didn't notice that they were different between the nasdaq, spr, invesco project.. thankyou!

**Comment by evdubs** [comment]
All set?

**Comment by CatspersCoffee** [comment]
almost, just have to run invesco, and then the oic, will work on this in the next couple hours

**Comment by CatspersCoffee** [comment]
so far getting for invesco:

```
./extract-transform-load.sh
/var/tmp/invesco/etf-holdings/2020-07-03/ADRU.csv
Failed to process ADRU for date 2020-07-03
(exn:fail:sql "query-exec: insert or update on table \"etf_holding\" violates foreign key constraint \"etf_holding_etf_symbol_fkey\"\n  SQLSTATE: 23503" #<continuation-mark-set> ...)
Attempted to insert 1 rows. 0 were successful. 1 failed.
/var/tmp/invesco/etf-holdings/2020-07-03/ADRD.csv
Failed to process ADRD for date 2020-07-03
(exn:fail:sql "query-exec: insert or update on table \"etf_holding\" violates foreign key constraint \"etf_holding_etf_symbol_fkey\"\n  SQLSTATE: 23503" #<continuation-mark-set> ...)
Attempted to insert 1 rows. 0 were successful. 1 failed.
/var/tmp/invesco/etf-holdings/2020-07-03/ADRA.csv
Failed to process ADRA for date 2020-07-03
(exn:fail:sql "query-exec: insert or update on table \"etf_holding\" violates foreign key constraint \"etf_holding_etf_symbol_fkey\"\n  SQLSTATE: 23503" #<continuation-mark-set> ...)
Attempted to insert 1 rows. 0 were successful. 1 failed.
/var/tmp/invesco/etf-holdings/2020-07-03/ADRE.csv
Attempted to insert 50 rows. 50 were successful. 0 failed.
```

looks like ADRE got loaded in the db (checked with pgAdmin), but ADRA, ADRD, ADRU did not get loaded. checked the .csv's and they definitely do have content and looks fine.. ill have a look into the ```violates foreign key constraint``` error

**Comment by evdubs** [comment]
For Invesco ADR ETFs, ADRA, ADRD, and ADRU were delisted back in February. You'll see in the CSVs that the date column shows when they were last active. I added a note to the invesco-etf-holdings project regarding this. The foreign key constraint violation is likely due to you not having the symbols in nasdaq.symbol because they were delisted. I will likely archive the invesco-etf-holdings project and try something else to analyze stocks that aren't in the S&P Large/Mid/Small cap ETFs.

**Comment by CatspersCoffee** [comment]
ok cool, yeah i did notice the date in the .csv file and can confirm ADRA etc are not in the nasdaq.symbol (s) act_symbols list. ok ill move onto oic

**Comment by CatspersCoffee** [comment]
running oic now. just with respect to running oic, this only downloads the current dates option chain information right? there is no way to probe the website for historical options chain data? ..sorry im not familiar with the website itself.

also, looking at your other project "renegade-way" --> say if i just wanted the rank , volatility analysis and option strategy portions only, what components could i omit in the build and/or database. i.e., i wouldn't be looking at the interface to IB.

thanks for your help and continued communication on this!

**Comment by evdubs** [comment]
Correct, the OIC project does not get history in one run. You'll build a history by running the extract periodically. I run it once every other day.

For rank and vol analysis, you'll need Zacks (estimates and earnings calendar; don't need financial statements) and OIC data.

**Comment by evdubs** [comment]
For the option strategy, you'll need UST yield curve data. I think you can get away with not having Yahoo dividends and just create the schema if you don't care about dividends with option pricing.

**Comment by CatspersCoffee** [comment]
ok so small update on running zacks estimates:

have the schema loaded in the db, estimate-extract.rkt worked fine, but running estimate-transform-load gives the following error for all symbols, ive checked that say A.detailed-estimates.html for each symbol is in the zacks/etstimates/2020-07-04 directory:

````
...continued from above...
Failed to process TNP for date 2020-07-04
(exn:fail:sql "query-exec: invalid input value for enum zacks.score: \"|\"\n  SQLSTATE: 22P02" #<continuation-mark-set> ...)
Failed to process EIG for date 2020-07-04
(exn:fail:sql "query-exec: invalid input value for enum zacks.score: \"|\"\n  SQLSTATE: 22P02" #<continuation-mark-set> ...)
Failed to process DISCB for date 2020-07-04
(exn:fail:contract "substring: starting index is out of range\n  starting index: 2\n  valid range: [0, 0]\n  string: \"\"" #<continuation-mark-set>)
Failed to process NICE for date 2020-07-04
(exn:fail:sql "query-exec: invalid input value for enum zacks.score: \"|\"\n  SQLSTATE: 22P02" #<continuation-mark-set> ...)
Failed to process GMTA for date 2020-07-04
(exn:fail:contract "substring: starting index is out of range\n  starting index: 2\n  valid range: [0, 0]\n  string: \"\"" #<continuation-mark-set>)
Attempted to insert 5603 rows. 0 were successful. 5603 failed.
````

**Comment by evdubs** [comment]
That looks strange. I will run the estimate ETL tomorrow and see what happens.

**Comment by CatspersCoffee** [comment]
awesome thanks! just looking at the rkt program and db schema, wondering if i messed something up, ill have a play around, otherwise i might try the earnings program today and see how far i get.

**Comment by CatspersCoffee** [comment]
same or similar deal with earnings-calendar:

```
...continued from above...
Failed to insert RANJY for date 2020-07-28
(exn:fail:sql "query-exec: insert or update on table \"earnings_calendar\" violates foreign key constraint \"earnings_calendar_act_symbol_fkey\"\n  SQLSTATE: 23503" #<continuation-mark-set> ...)
Failed to insert KIGRY for date 2020-07-28
(exn:fail:sql "query-exec: insert or update on table \"earnings_calendar\" violates foreign key constraint \"earnings_calendar_act_symbol_fkey\"\n  SQLSTATE: 23503" #<continuation-mark-set> ...)
Failed to insert NHYDY for date 2020-07-28
(exn:fail:sql "query-exec: insert or update on table \"earnings_calendar\" violates foreign key constraint \"earnings_calendar_act_symbol_fkey\"\n  SQLSTATE: 23503" #<continuation-mark-set> ...)
Failed to insert TKAGY for date 2020-07-28
(exn:fail:sql "query-exec: insert or update on table \"earnings_calendar\" violates foreign key constraint \"earnings_calendar_act_symbol_fkey\"\n  SQLSTATE: 23503" #<continuation-mark-set> ...)
```

**Comment by CatspersCoffee** [comment]
attached is the full log from running ```racket estimate-transform-load.rkt -d 2020-07-04```
[estimate.log](https://github.com/evdubs/nasdaq-symbols/files/4874390/estimate.log)

Hey, you mentioned i would need UST yield curve data to run the option strategy in renegade.. how do i go about obtaining this? (sorry a little lost on this one) or can i manually provide the risk free interest rate in ````pricing-risk.rkt```` somewhere? 

Thanks again for your help!

**Comment by evdubs** [comment]
Can you check the `zacks.earnings_calendar` in your DB? It is common for the OTC symbols to fail (they're not listed on NASDAQ). Those errors look normal.

Another aspect of the ETLs is that the Zacks processes will fail for a minority of stocks. For example, I think I usually see 3000 stocks processed successfully and less than 2000 with errors. I haven't tried to dig into these errors, but I do know that the universe of stocks does not always have an analyst for each stock.

There's a project github.com/evdubs/ust-yield-curve to get the yield curve.

**Comment by CatspersCoffee** [comment]
here is a screenshot of ````zacks.earnings_calendar```` ,i count 1 to 1000 rows in total. 

https://ibb.co/LQxDLQz

"but I do know that the universe of stocks does not always have an analyst for each stock" --> yeah this is what i assumed could be the case.

awesome thanks for the pointer to ```ust-yield-curve``` :-)

**Comment by evdubs** [comment]
zacks-estimates-financial-statements has been updated. Please pull it and run the `estimate-transform-load.rkt` script with the data you've already downloaded. I got:

> Attempted to insert 5610 rows. 3691 were successful. 1919 failed.

This is what looks to be normal.

**Comment by CatspersCoffee** [comment]
Awesome thanks, ive pulled and re-run on the data i had from the previous day, i get:

````Attempted to insert 5603 rows. 3690 were successful. 1913 failed.````

which seems to be in line with what you suggest is normal. Thankyou!

**Comment by evdubs** [comment]
The other projects now include "create schema" commands in their schema.sql files. I think we're well past the original issue here. Can you please open a new issue for whatever you find moving forward? It'll be nice to have it in the project where the issue occurs.
